version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 22
        commands:
            - echo "installing something"
            - yarn install
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - yarn build
            - echo "Exporting Next.js app..."
            - yarn next export
            - echo "Copying build files..."
            - mkdir -p artifact
            - cp -r out/* artifact/
    post_build:
        commands:
            - echo "we are in the post build phase"

artifacts:
    files:
        - '**/*'
    base-directory: artifact
    discard-paths: no